export const catalogCopy = {
	requesterTitle: "Look for groceries",
	managerTitle: "Product catalog",
	requesterIntro: "Look at the things you may need.",
	managerIntro: "Browse the curated catalog. Prices are approved demo prices, not real store offers.",
	browse: "Look at Groceries",
	home: "Home",
	familyHome: "Family Home",
	categoryLabel: "Choose a category",
	all: "All categories",
	searchLabel: "Find groceries",
	search: "Search",
	clear: "Show All",
	more: "More Groceries",
	first: "Back to First Groceries",
	previous: "Previous Groceries",
	loading: "Loading groceries…",
	empty: "There are no groceries to look at yet.",
	emptyHelp: "Ask your family member to help you.",
	managerEmpty: "No approved products have been seeded yet. Review the catalog dataset before seeding it.",
	noMatches: "We couldn't find any groceries like that.",
	noMatchesHelp: "Try another word or choose another category.",
	errorTitle: "We couldn't load the groceries",
	errorHelp: "Try again, or go back home.",
	retry: "Try Again",
	demoPrice: "Demo price",
	source: "Product data: Open Food Facts and Open Prices contributors, ODbL 1.0.",
	curatedSource: "Product data: CareBasket-curated demo product, ODbL 1.0.",
	simulation: "This store is simulated. No real orders or deliveries are placed.",
	readOnly: "Looking at groceries does not make a shopping request.",
	dataSources: "Data Sources",
	imageSource: "Image source",
	imageLicense: "CC BY-SA 3.0",
	results: ({ count }: { count: number }) => `${count} groceries on this page.`,
	productSearchLabel: "Search products",
	searchPlaceholder: "Try rice, milk, or bread",
	categorySelectLabel: "Category",
	activeFilters: "Active filters",
	managerLoading: "Loading products…",
	managerResults: ({ count }: { count: number }) =>
		`${count} ${new Intl.PluralRules("en-US").select(count) === "one" ? "product" : "products"} on this page`,
	pages: "Catalog pages",
	categories: {
		PRODUCE: "Fruits & Vegetables", DAIRY_EGGS: "Dairy & Eggs", BAKERY: "Bread & Bakery",
		PANTRY: "Rice & Pantry", BREAKFAST: "Breakfast", MEAT_SEAFOOD: "Meat & Fish",
		FROZEN: "Frozen Food", SNACKS: "Snacks", BEVERAGES: "Drinks",
		HOUSEHOLD: "Household Essentials", PERSONAL_CARE: "Personal Care",
	},
} as const;
