export const requestsCopy = {
	basketTitle: "Check your shopping list",
	basketIntro: "Make sure everything looks right before sending it to your family.",
	draftNotice: "Your unsent list stays here while you browse. Reloading or closing this page clears it.",
	browse: "Back to groceries", basket: "Check My List", history: "My Shopping Lists", home: "Home",
	emptyBasket: "Your shopping list is empty.", add: "Add to my list", remove: "Remove item", clear: "Clear my list",
	send: "Send My Shopping List", sending: "Sending your shopping list…",
	sent: "Your shopping list has been sent!", sentHelp: "Your family can now look at what you need.",
	view: "View Details", review: "Review request", inbox: "Shopping requests", listTitle: "My shopping lists",
	empty: "No shopping requests yet.", emptyHelp: "When someone in your family sends a shopping list, you'll see it here.",
	emptyHistory: "Your sent shopping lists will appear here.",
	childEmpty: "These products have not yet been reviewed for your shopping experience. Ask your family to help.",
	loading: "Loading shopping lists…", retry: "Try again", back: "Back to shopping lists", more: "More requests",
	quantity: "Quantity", decrease: (name: string) => `Decrease quantity for ${name}`,
	increase: (name: string) => `Increase quantity for ${name}`,
	added: (name: string) => `${name} added to your list.`,
	limit: "Your list can have up to 30 different products and 20 of each product.",
	count: (count: number) => `${count} ${count === 1 ? "product" : "products"}`,
	draftCount: (count: number) => `${count} ${count === 1 ? "product" : "products"} in your list`,
	managerTitle: (name: string) => `${name}'s shopping list`, substitute: "Substitute",
	pendingCount: (count: number) => `${count} ${count === 1 ? "request" : "requests"} waiting for review`,
	statuses: {
		PENDING_REVIEW: "Waiting for review", AWAITING_PAYMENT: "Payment not yet available",
		PAID: "Payment confirmed", DECLINED: "Declined", CANCELLED: "Cancelled",
	},
	explanations: {
		PENDING_REVIEW: "Your family can review this list. Nothing has been paid for or scheduled for delivery.",
		AWAITING_PAYMENT: "This list is waiting for your family. Payment is not available here.",
		PAID: "Your family has confirmed payment. This does not mean the groceries have been delivered.",
		DECLINED: "Your family declined this list. You can start a new shopping list.",
		CANCELLED: "You cancelled this list. You can start a new shopping list.",
	},
	demo: "CareBasket Demo Market prices · no real purchase",
	total: "Demo basket total", unit: "Demo unit price", line: "Demo line total",
	save: "Save quantity", saved: "Shopping list updated.", cancel: "Cancel this list", decline: "Decline request",
	keep: "Keep shopping list", confirm: "Yes, continue", closing: "Updating shopping list…",
	cancelTitle: "Cancel this shopping list?", declineTitle: "Decline this shopping request?",
	cancelHelp: "Your family will no longer review it. It stays in your shopping history.",
	declineHelp: "The list will stay in family history. Its status will be visible in CareBasket.",
	locked: "This list cannot be edited in its current status.",
	origins: { REQUESTED: "Selected by requester", SUGGESTED: "Suggested item" },
	original: "Original request", allStatuses: "All statuses", filter: "Filter requests", unavailable: "Shopping list not found",
	errorTitle: "We couldn't load shopping lists.",
	errorHelp: "Try loading this page again. Your unsent list has not been cleared.",
	errors: {
		UNAUTHENTICATED: "This device needs to be connected again. Ask your family to help.",
		FORBIDDEN: "You cannot change this shopping list.", NOT_FOUND: "This shopping list or item is no longer available.",
		VALIDATION_FAILED: "Check your list. Choose 1–20 of each product, with no more than 30 different products.",
		CONFLICT: "This list changed or is no longer editable. Refresh it before trying again. A different draft needs a new submission key.",
		RATE_LIMITED: "Too many shopping lists were sent from this device. Try again in an hour.",
		INTERNAL: "We couldn't save your shopping list. Your unsent list is still here; try again.",
	},
} as const;
