export const devicesCopy = {
	shopHome: "Home", askFamily: "Ask your family", skipShopping: "Skip to shopping",
	shopNav: "Shopping", shopProducts: "Products", shopList: "My List",
	shopHelp: "Ask your family member to help you.",
	shopDemo: "This is a demo. No real orders or deliveries.", loadingShopping: "Opening your shopping…",
  connectTitle: "Connect your device", connectDescription: "Someone in your family can help you start using CareBasket.",
  start: "Connect This Device", starting: "Getting your code…", codeLabel: "Your connection code",
  instructions: "Tell your family member this code so they can connect your device.",
  expires: "This code works for 10 minutes.", expiresSoon: "This code runs out in less than a minute.",
  waiting: "Waiting for your family member…", approved: "Your family member approved. Connecting…",
  expired: "This code has run out. Get a new code.", rejected: "Your family member did not connect this device. Get a new code when you are ready.",
  completed: "This code was already used. Open your CareBasket or connect again.",
  restart: "Get a New Code", retry: "Try Again", open: "Open My CareBasket",
  network: "We couldn't check your code. Check your connection and try again.",
  completionFailed: "We couldn't connect this device. Ask your family member to check it, or get a new code.",
  title: "Devices", description: "Manage the browsers connected to your family members.",
  connect: "Connect a Device", approvalTitle: "Connect a family member's device",
  approvalDescription: "On their device, open CareBasket /connect and choose Connect This Device. Enter the code shown there.",
  codeInput: "Six-digit code", codeHint: "Enter the code from the device you want to connect.", lookup: "Review Device",
  reviewTitle: "Review this connection", browserNotice: "This is a browser description, not proof of the device's physical identity. Confirm with your family member.",
  requested: "Requested", expiresAt: "Code expires", profile: "Family member", chooseProfile: "Choose a family member",
  timeRemaining: (time: string) => `Time left: ${time}`,
  utc: "UTC",
  label: "Device label", labelHint: "Use a short name, for example Grandma's iPad.",
  confirmation: "I checked with my family member and want to connect this browser to the selected profile.",
  approve: "Approve Connection", reject: "Reject Connection", rejectedManager: "Connection rejected.", approvedManager: "Approved. Keep the requesting device open to finish connecting.",
  busy: "Saving…", checking: "Checking…", empty: "No connected devices yet.",
  noProfiles: "Add a family member before connecting a device.", addProfile: "Add Family Member",
  connected: "Connected", lastActivity: "Last used", states: { ACTIVE: "Active", EXPIRED: "Expired", REVOKED: "Revoked" },
  revoke: "Disconnect Device", revokeTitle: (label: string) => `Disconnect ${label}?`,
  revokeText: "This browser will need a new connection code before it can use CareBasket again.",
  revokeConfirm: "I want to disconnect this device.", revoked: "Device disconnected.", cancel: "Cancel",
  next: "More Devices", first: "Back to First Devices", moreProfiles: "More Family Members", backDevices: "Back to Devices",
  loading: "Loading devices…", loadingApproval: "Loading the connection form…", errorTitle: "We couldn't open CareBasket", errorText: "Please try again in a moment.",
  reconnect: "This device needs to be connected again.", reconnectHelp: "Ask your family member to help you.", reconnectAction: "Connect Again",
  greeting: (name: string) => `Hello, ${name}!`, welcome: "Your CareBasket is ready.",
  shopping: "Choose groceries, check your list, and send it to your family.", reviewNotice: "Your family member will review every shopping request.",
  comingSoon: "Voice and text requests are coming next. You can choose groceries by picture now.",
  disclaimer: "CareBasket is an independent project and is not affiliated with or endorsed by PayPal.",
  errors: { code: "Enter the six digits shown on their device.", label: "Enter a label of 40 characters or fewer, without hidden characters.",
    confirm: "Confirm that you checked the device and selected the right person.",
    UNAUTHENTICATED: "This connection is no longer available. Get a new code.",
    FORBIDDEN: "You don't have permission to connect devices.", NOT_FOUND: "We couldn't find that. Check the code or get a new one.",
    CONFLICT: "This connection changed or the person already has five active devices. Refresh and try again.",
    RATE_LIMITED: "Please wait before trying again. Too many attempts were made.", VALIDATION_FAILED: "Please check the highlighted fields.",
    INTERNAL: "We couldn't finish that. Please try again in a moment." },
} as const;
