export const profilesCopy = {
  title: "Family Members",
  description: "Simple profiles for the people you help with shopping.",
  add: "Add Family Member",
  adding: "Adding family member…",
  edit: "Edit Profile",
  save: "Save Changes",
  saving: "Saving changes…",
  view: "View Profile",
  back: "Back to Family Members",
  dashboard: "Back to Family Overview",
  cancel: "Cancel",
  emptyTitle: "Who would you like to help?",
  emptyText: "Add someone you care for. They won't need an email address or password.",
  addTitle: "Add a family member",
  addDescription: "A first name or nickname is all we need to get started.",
  editTitle: "Edit family member",
  editDescription: "Update their name or avatar. Their profile type stays the same.",
  nameLabel: "What should we call them?",
  nameHint: "Use a first name or nickname.",
  nameExample: "Grandma Rose",
  kindLabel: "Profile type",
  kinds: { ASSISTED_ADULT: "Assisted Adult", CHILD: "Child" },
  kindDescriptions: {
    ASSISTED_ADULT: "For a parent, grandparent, or adult who wants help shopping.",
    CHILD: "For a child whose shopping requests are supervised by an adult.",
  },
  avatarLabel: "Choose an avatar",
  avatars: { smile: "Smile", sun: "Sun", flower: "Flower", leaf: "Leaf" },
  chosen: "Chosen",
  consentLabel: "Consent",
  consent: "I am this person's parent or guardian, or they have asked me to set this up for them.",
  consentHint: "Assisted adults must know and agree. For a child, you must be their parent or authorized guardian.",
  aiNotice: "AI assistance is off. Enabling it will require separate consent in a later step.",
  detailTitle: "Family member profile",
  familyLabel: "Family",
  createdLabel: "Added on",
  deviceNotice: "This person can start requesting groceries once their device is connected.",
  deviceUnavailable: "Device connection is coming in a later step.",
  remove: "Remove Profile",
  removing: "Removing profile…",
  removeTitle: (name: string) => `Remove ${name}?`,
  removeText: (name: string) => `This permanently removes ${name}'s profile from your family. This cannot be undone.`,
  removeConfirm: (name: string) => `I confirm that I want to permanently remove ${name}'s profile.`,
  loading: "Loading family members…",
  next: "More Family Members",
  first: "Back to first members",
  notFoundTitle: "Profile not found",
  notFoundText: "We couldn't find that family member. Return to your family members to continue.",
  errorTitle: "We couldn't load family members",
  errorText: "Please try again in a moment.",
  retry: "Try again",
  validationSummary: "Please check the highlighted fields.",
  errors: {
    nameRequired: "Enter a first name or nickname.",
    nameLength: "Use 40 characters or fewer.",
    nameUnsafe: "Remove hidden or special characters.",
    kind: "Choose Assisted Adult or Child.",
    avatar: "Choose one of the preset avatars.",
    consent: "Confirm their permission or your guardianship before adding a profile.",
    confirmation: "Confirm that you want to permanently remove this profile.",
    forbidden: "You don't have permission to manage family members.",
    unauthenticated: "Please sign in again.",
    notFound: "We couldn't find that family member.",
    internal: "We couldn't save that change. Please try again in a moment.",
  },
} as const;
